#!/usr/bin/env bash
# One-command local bootstrap for pi-as-mcp + OpenAI Secure MCP Tunnel.
set -euo pipefail
cd "$(dirname "$0")/.."

MIN_NODE_MAJOR=22
MIN_NODE_MINOR=19

usage() {
	cat <<'EOF'
Usage: ./scripts/setup.sh [--non-interactive] [--refresh-tunnel-client]

Installs dependencies with bun, builds pi-as-mcp, installs the pinned OpenAI
`tunnel-client`, and creates/updates the local tunnel configuration.

Options:
  --non-interactive       Never prompt. Existing tunnel/.env is preserved;
                          if it is missing, create it from .env.example.
  --refresh-tunnel-client Reinstall the pinned tunnel-client build.
  -h, --help              Show this help.
EOF
}

INTERACTIVE=true
REFRESH_TUNNEL=false
while [ "$#" -gt 0 ]; do
	case "$1" in
		--non-interactive) INTERACTIVE=false ;;
		--refresh-tunnel-client) REFRESH_TUNNEL=true ;;
		-h|--help) usage; exit 0 ;;
		*) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
	esac
	shift
done

if [ ! -t 0 ]; then
	INTERACTIVE=false
fi

if ! command -v node >/dev/null 2>&1; then
	echo "Node.js >= ${MIN_NODE_MAJOR}.${MIN_NODE_MINOR} is required." >&2
	exit 1
fi
if ! node -e '
const [major, minor] = process.versions.node.split(".").map(Number);
if (major < 22 || (major === 22 && minor < 19)) process.exit(1);
'; then
	echo "Node.js >= ${MIN_NODE_MAJOR}.${MIN_NODE_MINOR} is required; found $(node --version)." >&2
	exit 1
fi

if ! command -v bun >/dev/null 2>&1; then
	echo "Bun is required to install dependencies and run scripts. Install it from https://bun.com" >&2
	exit 1
fi

printf '\n==> Installing dependencies\n'
bun install

printf '\n==> Building pi-as-mcp\n'
bun run build

if [ "$REFRESH_TUNNEL" = true ] || [ ! -x bin/tunnel-client ]; then
	printf '\n==> Installing OpenAI tunnel-client\n'
	./scripts/tunnel-install.sh
else
	printf '\n==> OpenAI tunnel-client already installed: '
	./bin/tunnel-client --version
fi

mkdir -p tunnel

is_placeholder() {
	case "${1:-}" in
		""|tunnel_paste_your_tunnel_id_here|sk_paste_your_runtime_key_here) return 0 ;;
		*) return 1 ;;
	esac
}

shell_quote() {
	# Emit a value safe to source from the bash dotenv file.
	local escaped=${1//\'/\'\\\'\'}
	printf "'%s'" "$escaped"
}

if [ -d "${HOME}/dev" ]; then
	PI_MCP_CWD_VALUE="${HOME}/dev"
else
	PI_MCP_CWD_VALUE="$(pwd)/sandbox"
fi
PI_MCP_TOOLS_VALUE=""
PI_MCP_BASH_MAX_SYNC_SECONDS_VALUE="20"
CONTROL_PLANE_TUNNEL_ID_VALUE=""
CONTROL_PLANE_API_KEY_VALUE=""

if [ -f tunnel/.env ]; then
	chmod 600 tunnel/.env
	set -a
	# shellcheck disable=SC1091
	. ./tunnel/.env
	set +a
	PI_MCP_CWD_VALUE="${PI_MCP_CWD:-$PI_MCP_CWD_VALUE}"
	PI_MCP_TOOLS_VALUE="${PI_MCP_TOOLS:-}"
	PI_MCP_BASH_MAX_SYNC_SECONDS_VALUE="${PI_MCP_BASH_MAX_SYNC_SECONDS:-$PI_MCP_BASH_MAX_SYNC_SECONDS_VALUE}"
	CONTROL_PLANE_TUNNEL_ID_VALUE="${CONTROL_PLANE_TUNNEL_ID:-}"
	CONTROL_PLANE_API_KEY_VALUE="${CONTROL_PLANE_API_KEY:-}"
fi

if [ "$INTERACTIVE" = true ]; then
	printf '\n==> Local configuration\n'
	printf 'Workspace root [%s]: ' "$PI_MCP_CWD_VALUE"
	IFS= read -r input
	if [ -n "$input" ]; then PI_MCP_CWD_VALUE="$input"; fi
	if [ ! -d "$PI_MCP_CWD_VALUE" ]; then
		echo "Workspace root does not exist: $PI_MCP_CWD_VALUE" >&2
		exit 1
	fi

	if is_placeholder "$CONTROL_PLANE_TUNNEL_ID_VALUE"; then
		printf 'OpenAI tunnel ID: '
		IFS= read -r CONTROL_PLANE_TUNNEL_ID_VALUE
	else
		printf 'OpenAI tunnel ID [configured; Enter to keep]: '
		IFS= read -r input
		if [ -n "$input" ]; then CONTROL_PLANE_TUNNEL_ID_VALUE="$input"; fi
	fi

	if is_placeholder "$CONTROL_PLANE_API_KEY_VALUE"; then
		printf 'OpenAI runtime API key: '
		IFS= read -r -s CONTROL_PLANE_API_KEY_VALUE
		printf '\n'
	else
		printf 'OpenAI runtime API key [configured; Enter to keep]: '
		IFS= read -r -s input
		printf '\n'
		if [ -n "$input" ]; then CONTROL_PLANE_API_KEY_VALUE="$input"; fi
	fi

	{
		cat <<'EOF'
# Local pi-as-mcp / OpenAI Secure MCP Tunnel configuration.
# Generated by `bun run setup`. This file is gitignored and must remain private.

EOF
		printf 'PI_MCP_CWD=%s\n' "$(shell_quote "$PI_MCP_CWD_VALUE")"
		if [ -n "$PI_MCP_TOOLS_VALUE" ]; then
			printf 'PI_MCP_TOOLS=%s\n' "$(shell_quote "$PI_MCP_TOOLS_VALUE")"
		fi
		printf 'PI_MCP_BASH_MAX_SYNC_SECONDS=%s\n' "$(shell_quote "$PI_MCP_BASH_MAX_SYNC_SECONDS_VALUE")"
		printf 'CONTROL_PLANE_TUNNEL_ID=%s\n' "$(shell_quote "$CONTROL_PLANE_TUNNEL_ID_VALUE")"
		printf 'CONTROL_PLANE_API_KEY=%s\n' "$(shell_quote "$CONTROL_PLANE_API_KEY_VALUE")"
	} > tunnel/.env
	chmod 600 tunnel/.env
elif [ ! -f tunnel/.env ]; then
	install -m 600 tunnel/.env.example tunnel/.env
	printf '\nCreated tunnel/.env from the template. Fill in the tunnel ID and runtime key before starting.\n'
fi

if [ -f tunnel/.env ]; then
	chmod 600 tunnel/.env
fi

printf '\n==> Setup complete\n'
if is_placeholder "$CONTROL_PLANE_TUNNEL_ID_VALUE" || is_placeholder "$CONTROL_PLANE_API_KEY_VALUE"; then
	cat <<'EOF'
Edit tunnel/.env, then validate and start with:

  bun run tunnel:doctor
  bun run tunnel
EOF
else
	cat <<'EOF'
Validate and start with:

  bun run tunnel:doctor
  bun run tunnel

Once running:

  bun run tunnel:status
  bun run tunnel:ui
EOF
fi
